<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename = "inertial_macros.xacro" />

    <xacro:property name="chassis_length"           value="0.360"/>
    <xacro:property name="chassis_width"            value="0.250"/>
    <xacro:property name="chassis_height"           value="0.150"/>
    <xacro:property name="chassis_mass"             value="0.500"/>

    <xacro:property name="wheel_radius"             value="0.034"/>
    <xacro:property name="wheel_thickness"          value="0.030"/>
    <xacro:property name="wheel_mass"               value="0.100"/>
    <xacro:property name="wheel_offset_x"           value="0"/>
    <xacro:property name="wheel_offset_y"           value="0.135"/>
    <xacro:property name="wheel_offset_z"           value="0"/>

    <xacro:property name="caster_wheel_radius"      value="${wheel_radius - wheel_offset_z}"/>
    <xacro:property name="caster_wheel_mass"        value="0.010"/>
    <xacro:property name="caster_wheel_offset_x"    value="0.230"/>
    <xacro:property name="caster_wheel_offset_z"    value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>


    <!-- Colors -->
    <material name="white">
        <color rgba= "1 1 1 1"/>    
    </material>
    
    <material name="black">
        <color rgba= "0 0 0 1"/>    
    </material>
    
    <material name= "orange">
        <color rgba= "1 0.25 0 1"/>    
    </material>

    <material name="cyan">
        <color rgba= "0 1 1 1"/>    
    </material>

    <material name="indigo">
        <color rgba= "0.294 0 0.51 1"/>    
    </material>


    <!-- convention (except base_link): joint followed by link -->
    <!-- base_link -->
    <link name="base_link">
    </link>

    <!-- base_footprint -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link= "base_link"/>
        <child link= "base_footprint"/>
        <origin xyz= "0 0 0" rpy= "0 0 0"/>    
    </joint>

    <link name="base_footprint">
    </link>

    <!-- chasis -->
    <joint name="chasis_joint" type="fixed">
        <parent link= "base_link"/>
        <child link= "chasis"/>
        <origin xyz= "-0.1 0 0"/>    
    </joint>

    <link name="chasis">
        <visual>
            <origin xyz= "0.18 0 0.075" rpy= "0 0 0"/>
            <geometry>
                <box size = "0.36 0.25 0.15"/>
            </geometry>
            <material name= "black"/>
        </visual>
        <collision>
            <origin xyz= "0.18 0 0.075" rpy= "0 0 0"/>
            <geometry>
                <box size = "0.36 0.26 0.15"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass= "0.5" x="0.36" y="0.26" z="0.15">
            <origin xyz= "0.18 0 0.075" rpy= "0 0 0"/>
        </xacro:inertial_box>
    </link> 

    <gazebo reference="chasis">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- left_wheel -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link= "base_link"/>
        <child link= "left_wheel"/>
        <origin xyz= "0 0.135 0" rpy = "${pi/2} 0 0"/>
        <axis xyz= "0 0 -1"/>    
    </joint>

    <link name="left_wheel"> 
        <visual>
            <geometry>
                <cylinder radius = "0.034" length= "0.03"/>
            </geometry>
            <material name= "orange"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius = "0.034" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass = "0.1" radius= "0.034" length= "0.03">
            <origin xyz= "0 0 0" rpy= "0 0 0"/>
        </xacro:inertial_cylinder>
    </link> 

    <gazebo reference="left_wheel">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- right_wheel -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link= "base_link"/>
        <child link= "right_wheel"/>
        <origin xyz= "0 -0.135 0" rpy = "${pi/2} 0 0"/>
        <axis xyz= "0 0 -1"/>    
    </joint>

    <link name="right_wheel"> 
        <visual>
            <geometry>
                <cylinder radius = "0.034" length= "0.03"/>
            </geometry>
            <material name= "orange"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius = "0.034" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass = "0.1" radius= "0.034" length= "0.03">
            <origin xyz= "0 0 0" rpy= "0 0 0"/>
        </xacro:inertial_cylinder>
    </link> 

    <gazebo reference="right_wheel">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- caster_wheel -->
    <joint name="caster_wheel_joint" type="fixed">
        <parent link= "chasis"/>
        <child link= "caster_wheel"/>
        <origin xyz= "0.30 0 0"/>   
    </joint>

    <link name="caster_wheel"> 
        <visual>
            <geometry>
                <sphere radius = "0.025"/>
            </geometry>
            <material name= "orange"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius = "0.025"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass= "0.1" radius= "0.025">
            <origin xyz= "0 0 0" rpy= "0 0 0"/>
        </xacro:inertial_sphere>
    </link> 

    <gazebo reference="caster_wheel">
        <material>Gazebo/Orange</material>
        <mu1 value= "0.0001"/>
        <mu2 value= "0.0001"/>
    </gazebo>


</robot>